version: '3'
services:
  db:
    container_name: main-db
    image: postgres:alpine
    environment:
      POSTGRES_USER: salabridge
      POSTGRES_DB: salabridge
      POSTGRES_PASSWORD: supersecure
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:
